linode/linode-cloud-controller-manager

CONTRIBUTING.md, README.md
Hey y'all.
Whipping together some generic contributor guidelines. Let me know what you think.
=> Add contributor info

Dockerfile, Gopkg.lock, docs/developer-guide/README.md, hack/builddeps.sh, hack/deploy/ccm-linode-template.yaml, hack/deploy/generate-manifest.sh, hack/deploy/uninstall.sh
* Update manifests to use a DaemonSet with appropriate Tolerations
* Add a shell script to generate the manifest
* Update developer documentation on the use Dep
* Update uninstall script
=> Update manifests and developer documentation

cloud/linode/loadbalancers.go
* [ x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x ] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?
=> Fix Node balancer comments

cloud/linode/loadbalancers.go
* [ x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x ] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?
=> Use Correct port for config node

cloud/linode/fake_linode_test.go, cloud/linode/loadbalancers.go, cloud/linode/loadbalancers_test.go, vendor/github.com/linode/linodego/nodebalancer_configs.go
=> Fix update node balancer filtering

e2e/README.md
=> Inform users about ssh-agent when running e2e tests

e2e/test/ccm_e2e_test.go, e2e/test/framework/service.go
=> Add Test for SessionAffinity

e2e/go.mod, e2e/go.sum, e2e/test/ccm_e2e_test.go, e2e/test/ccm_suite_test.go, e2e/test/framework/framework.go, e2e/test/framework/loadbalancer_suit.go, e2e/test/framework/service.go
=> Add Test for LoadBalancer Service for HTTP Body Health Checks

e2e/go.mod, e2e/go.sum, e2e/test/ccm_e2e_test.go, e2e/test/ccm_suite_test.go, e2e/test/framework/framework.go, e2e/test/framework/loadbalancer_suit.go, e2e/test/framework/service.go
=>  Add Test for LoadBalancer Service for with Node Addition

README.md, deploy/generate-manifest.sh
=> Fix a couple of directions

CHANGELOG.md
I forgot to add an unreleased changelog entry for the CCM fixes, so I added that here.
=> Updated changelog for v0.3.1

deploy/generate-manifest.sh
=> Avoid new lines when base64 encoding values

deploy/generate-manifest.sh
Reverts linode/linode-cloud-controller-manager#59
=> Revert "Avoid new lines when base64 encoding values"

e2e/Makefile, e2e/README.md, e2e/test/ccm_e2e_test.go, e2e/test/ccm_suite_test.go, e2e/test/framework/service.go
Ultimately, the bug I am hunting for was not uncovered, but might as well keep the test.
=> Add test for adding a tls port

cloud/linode/instances.go
Minor change
`s/the the /the /g`
=> Fix typo, minor change

cloud/linode/instances.go, cloud/linode/instances_test.go
Should close #67 
When a node becomes `NotReady`, the CCM's node controller will call upon `InstanceShutdownByProviderID` to determine whether or not the node has been powered off. If the cloud provider has implemented this function, it will return true when the instance is deemed to be shutdown, and the CCM will then proceed to add [shutdown-based taints](https://github.com/kubernetes/kubernetes/blob/cb303e613a121a29364f75cc67d3d580833a7479/staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller.go#L181) that will evict the pods from the node.
1. [x] Are you following …
=> Add support to detect for powered-off nodes

.gitignore, README.md, deploy/.gitignore, deploy/chart/.helmignore, deploy/chart/Chart.yaml, deploy/chart/templates/_helpers.tpl, deploy/chart/templates/ccm-linode.yaml, deploy/chart/templates/clusterrole-rbac.yaml, deploy/chart/templates/clusterrolebinding-rbac.yaml, deploy/chart/templates/daemonset.yaml, deploy/chart/templates/serviceaccount.yaml, deploy/chart/values.yaml
Creating the helm chart for linode-ccm to help streamline the deployment and make is more efficient.
Updated README to include Helm Chart info - added a new section on how to deploy using the helm chart for Linode-CCM
=> Create a Helm Chart

.github/workflows/helm.yml
=> store helm packages directly in the Github page

.github/workflows/helm.yml
=> restrict helm releases to be triggered by Github releases

cloud/linode/node_controller.go
This bug got accidentally introduced in https://github.com/linode/linode-cloud-controller-manager/pull/175, adding one line change to get the fix in.
=> fix adding labels to node

README.md, cloud/linode/loadbalancers.go, cloud/linode/loadbalancers_test.go
=> disable conn-throttle by default

README.md
Fix typo in README where in example is invalid json.
=> fix-readme: firewall-acl invalid json

README.md
=> Fix Test Badge

deploy/chart/templates/daemonset.yaml
=> [fix] update helm templating for loadBalancerType

.github/workflows/ci.yml, Makefile, README.md
=> Add support for codecov reporting

deploy/chart/templates/daemonset.yaml
Follow-up from https://github.com/linode/linode-cloud-controller-manager/pull/224
=> [fix] udpate helm chart for excluding bgp node selector

cloud/linode/instances.go, cloud/linode/loadbalancers.go
- Add logs to node IP addresses for enhanced visibility.
=> Add logs to node IP addresses.

.github/dependabot.yml
=> [enhancement] : add dependabot support

Dockerfile, devbox.json, devbox.lock, go.mod
This PR updates CCM to use golang 1.23
=> [deps] : bump golang to 1.23

.github/workflows/ci.yml
Instead of using latest, pin golangci-lint version to supported version and have dependabot update it when required.
=> [deps] : pin golangci-lint version

cloud/linode/cloud_test.go, cloud/linode/node_controller_test.go, cloud/linode/service_controller_test.go, codecov.yml
Update codecoverage for the repo
=> [test] : add more unittests to increase code-coverage

cloud/linode/firewall/firewalls.go, cloud/linode/loadbalancers.go, e2e/test/lb-fw-delete-acl/chainsaw-test.yaml, e2e/test/lb-fw-delete-acl/create-pods-services.yaml
Previously, on deletion of service which had ACL annotation for firewall config, those firewalls created by CCM were not cleaned up. This PR adds logic to clean such firewalls created by CCM.
=> [fix] : delete fw if provisioned by CCM with ACL

.github/workflows/ci.yml
=> [CI] : use pull_request_target for CI workflows

cloud/linode/firewall/firewalls.go, cloud/linode/loadbalancers_test.go
This PR fixes https://github.com/linode/linode-cloud-controller-manager/issues/308
Firewall rule's description has a limit of 100 chars. This PR makes sure we don't go over the limit.
=> [fix] : limit fw-rule description to 100 chars

.github/workflows/ci.yml
=> [CI] : allow golangci-lint.run url

e2e/test/ccm-resources/chainsaw-test.yaml, e2e/test/fw-use-specified-nb/chainsaw-test.yaml, e2e/test/lb-created-with-new-nb-id/chainsaw-test.yaml, e2e/test/lb-created-with-specified-nb-id/chainsaw-test.yaml, e2e/test/lb-delete-svc-no-nb/chainsaw-test.yaml, e2e/test/lb-delete-svc-use-new-nbid/chainsaw-test.yaml, e2e/test/lb-delete-svc-use-specified-nb/chainsaw-test.yaml, e2e/test/lb-fw-delete-acl/chainsaw-test.yaml, e2e/test/lb-fw-update-acl/chainsaw-test.yaml, e2e/test/lb-hostname-only-ingress/chainsaw-test.yaml, e2e/test/lb-http-body-health-check/chainsaw-test.yaml, e2e/test/lb-http-status-health-check/chainsaw-test.yaml, e2e/test/lb-passive-health-check/chainsaw-test.yaml, e2e/test/lb-preserve-annotation-new-nb-specified/chainsaw-test.yaml, e2e/test/lb-preserve-annotation-svc-delete/chainsaw-test.yaml, e2e/test/lb-simple/chainsaw-test.yaml, e2e/test/lb-single-tls/chainsaw-test.yaml, e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml, e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml, e2e/test/lb-with-http-to-https/chainsaw-test.yaml, e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml, e2e/test/lb-with-node-addition/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-default-annotation/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-override/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-port-specific/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-set/chainsaw-test.yaml, e2e/test/route-controller-test/chainsaw-test.yaml
This PR separates out CCM resource check into a separate test and removes it from all other tests.
=> [test] : add ccm resource check as separate test

.github/workflows/build-test.yml, .github/workflows/ci.yml
This PR moves the steps which don't require access to secrets into a separate workflow. This new workflow can then use the branch's workflow file and can test the initial code even from forked repos without waiting for approval for tasks which don't even require secrets.
1. [ ] Have you linked your PR to an [open …
=> [CI] : move steps which don't require secrets to separate workflow

Makefile, e2e/bgp-test/lb-cilium-bgp/chainsaw-test.yaml, e2e/test/ccm-resources/chainsaw-test.yaml, e2e/test/fw-use-specified-nb/chainsaw-test.yaml, e2e/test/lb-created-with-new-nb-id/chainsaw-test.yaml, e2e/test/lb-created-with-specified-nb-id/chainsaw-test.yaml, e2e/test/lb-delete-svc-no-nb/chainsaw-test.yaml, e2e/test/lb-delete-svc-use-new-nbid/chainsaw-test.yaml, e2e/test/lb-delete-svc-use-specified-nb/chainsaw-test.yaml, e2e/test/lb-fw-delete-acl/chainsaw-test.yaml, e2e/test/lb-fw-update-acl/chainsaw-test.yaml, e2e/test/lb-hostname-only-ingress/chainsaw-test.yaml, e2e/test/lb-http-body-health-check/chainsaw-test.yaml, e2e/test/lb-http-status-health-check/chainsaw-test.yaml, e2e/test/lb-passive-health-check/chainsaw-test.yaml, e2e/test/lb-preserve-annotation-new-nb-specified/chainsaw-test.yaml, e2e/test/lb-preserve-annotation-svc-delete/chainsaw-test.yaml, e2e/test/lb-simple/chainsaw-test.yaml, e2e/test/lb-single-tls/chainsaw-test.yaml, e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml, e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml, e2e/test/lb-with-http-to-https/chainsaw-test.yaml, e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml, e2e/test/lb-with-node-addition/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-default-annotation/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-override/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-port-specific/chainsaw-test.yaml, e2e/test/lb-with-proxyprotocol-set/chainsaw-test.yaml, e2e/test/route-controller-test/chainsaw-test.yaml
This PR adds labels for e2e tests so that one can select specific tests when running agaist different kinds of clusters.
=> [test] : add labels to run e2e tests

docs/configuration/annotations.md
Fixes https://github.com/linode/linode-cloud-controller-manager/issues/359
=> [docs] : update doc with correct type and note to specify values as string

e2e/test/lb-http-body-health-check/chainsaw-test.yaml, e2e/test/lb-http-status-health-check/chainsaw-test.yaml, e2e/test/lb-passive-health-check/chainsaw-test.yaml, e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml, e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml, e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml, e2e/test/lb-with-node-addition/chainsaw-test.yaml
=> [CI] : increase retries count for node-addition test

cloud/linode/loadbalancers.go, cloud/linode/loadbalancers_test.go
The current implementation of `getNodeBalancerByStatus` assumes that Ingress IPs are always v4, but that is not true when the  `service.beta.kubernetes.io/linode-loadbalancer-enable-ipv6-ingress` annotation is set on a Service. This PR fixes the issue …
=> [fix]: Fix getNodeBalancerByStatus bug when IPv6 ingress is enabled

index.yaml
remove invalid release from index.yaml
=> [CI] Update index.yaml

.github/copilot-instructions.md
=> [chore] Add copilot instructions

.github/workflows/build-test.yml, .github/workflows/ci.yml
This PR allows all *.githubusercontent.com urls to prevent workflows from failing when they try to access new URLs published by github.
=> [CI] : allow all githubusercontent.com urls

go.mod, go.sum
Since the required changes are now in upstream linodego, we should use that instead of forked repo's branch.
=> [deps] : use upstream linodego instead of forked repo's linodego
