linode/linode-cloud-controller-manager

e2e/test/ccm_e2e_test.go
e2e/test/framework/framework.go
e2e/test/framework/pod.go
e2e/test/framework/secret.go
e2e/test/framework/service.go
e2e/test/framework/util.go

 Add Test for LoadBalancer Service with 2 Ports

---

cloud/linode/cloud.go

The oauth2.Transport we were previously creating here was a valid
http.RoundTripper, but was not an http.Transport. Resty (which
linodego also uses) expects the transport to be an http.Transport for
certain features.
Requires https://github.com/linode/linodego/pull/80

Use default linodego http client rather than creating a custom one

---

Dockerfile
Makefile

Perhaps a `clean` dependency on the `build` targets?

In Makefile and Dockerfile, /ccm-linode/linode-cloud-controller-manager/

---

cloud/linode/cloud.go
cloud/linode/loadbalancers.go
main.go

When explicitly passing a kubeconfig via --kubeconfig, the CCM would use the provided kubeconfig but Linode-specific logic would not. This would lead to errors when attempting to use a Kubernetes client to get TLS secrets, as the CCM was attempting to get those from the cluster it was in as opposed to the cluster it was pointing to based on the given kubeconfig.
This addresses that issue by defining and setting a KubeconfigFlag option in linode.Options, then using that when creating a Kubernetes client. The presence of the flag in the flag set is required, but its use is not; if --kubeconfig is not set, the CCM will default to authenticating using the in-cluster config.
I'm pretty sure this works, but still need to test it 👼 Placing it here now for review.

Added KubeconfigFlag option based on CCM --kubeconfig flag

---

e2e/test/framework/loadbalancer_suit.go

Adding error checking when listing NBs seems to have been missed earlier. This takes care of that.

Add error checking when listing NodeBalancers

---

cloud/linode/fake_linode_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

It turns out that according to [the API spec](https://developers.linode.com/api/v4/nodebalancers-node-balancer-id-configs/#post), and contrary to [linodego](https://github.com/linode/linodego/blob/master/nodebalancer_configs.go#L104), NodeBalancer configs do not get populated with nodes at create time; they only get populated with nodes at rebuild time. As a result, LoadBalancer services that were created, then updated with new ports weren't getting nodes associated with those ports.
This pull request resolves that issue by creating configs for ports that don't exist, then rebuilding all configs for all ports.

Rebuild all NodeBalancer configs on update

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Bugfix: Updating NodeBalancer port configs is broken. If you attempt to update a port configuration, the NodeBalancer does not update.
This PR addresses this and ensures NodeBalancer port configs are updated correctly.

Ensure rebuild options are captured correctly if NodeBalancer config exists

---

deploy/generate-manifest.sh

Fix manifest generation on macOS

Avoid new lines when base64 encoding values

---

deploy/ccm-linode-template.yaml

1. [X] Have you explained your rationale for why this feature is needed? 
The logs show that the CCM listens insecurely on port 10253:
```
...
ERROR: logging before flag.Parse: I0310 17:35:16.742438       1 flags.go:27] FLAG: --port="10253"
...
ERROR: logging before flag.Parse: I0310 17:35:16.944444       1 …
```

Disable insecure port, enable secure port on 10253

---

.golangci.yml
.travis.yml
README.md
cloud/linode/fake_linode_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
e2e/go.sum
e2e/test/ccm_e2e_test.go
e2e/test/ccm_suite_test.go
e2e/test/framework/loadbalancer_suit.go

This change adds an annotation that can be used on services of `type: LoadBalancer` to ensure that the underlying NodeBalancer is not deleted when the service is.
This is the first of two PRs to enable reusing LoadBalancers.

Add loadbalancer preserve annotation

---

go.mod
go.sum

The Goautoneg bitbucket repo has been deprecated, due to bitbucket deprecating support for mercurial repos. This causes CCM build to fail. The bitbucket repo has been mirrored on github, however it seems that some dependencies have not yet been updated to point to it. This instead adds a replace directive to use the github mirror, rather than the dead bitbucket repo.
1. …

Add replace directive in go.mod for deprecated goautoneg bitbucket repo

---

e2e/go.mod
e2e/go.sum

Add replace for goautoneg bitbucket repo to e2e go.mod. This repo no longer exists and is an indirect dependency.

Add replace for goautoneg bitbucket repo to e2e go.mod

---

README.md
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_deprecated.go
cloud/linode/loadbalancers_test.go
e2e/test/ccm_e2e_test.go
e2e/test/framework/loadbalancer_suite.go

Closes #84.
These changes add a `proxy-protocol` field to the `port-*` annotation and deprecate the `proxy-protocol` annotation in favor of `default-proxy-protocol`. The deprecated annotation will be removed in Q4 of 2021.

allow configuring proxy-protocol per port

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
e2e/test/ccm_e2e_test.go
e2e/test/framework/loadbalancer_suite.go
e2e/test/framework/service.go
e2e/test/framework/util.go

Closes #74
This changes the LoadBalancer status we return from `EnsureLoadBalancer` and `GetLoadBalancer` to only include the NodeBalancer hostname and not the IPv4 address. Omitting the IP ensures kube-proxy does not insert rules to hijack requests to the external LB IP from within the cluster to resolve to the cluster IP for the underlying pod. This proxying caused issues for users expecting the NodeBalancer to include proxy-protocol headers. See #74.
Due to LoadBalancer statuses not including the LB IPv4 address, LB discovery will now be done using the hostname.

allow inter-service communication from within cluster via external LB

---

README.md
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
e2e/test/ccm_e2e_test.go
e2e/test/framework/loadbalancer_suite.go

This annotation will allow users to use short-circuit adding the underlying NodeBalancer's IP to the LoadBalancerStatus (see #87). This is now an opt-in feature as it's much quicker to expose the IPv4 as an interface for the service than waiting for the DNS A record to be propagated for the hostname.

add loadbalancer-hostname-only-ingress annotation

---

.github/workflows/docker-hub.yml
.github/workflows/label-sync.yml
.github/workflows/release-drafter.yml

- Alters all workflows to reference actions by their commit SHA rather than their version/tag
- Addresses security concerns described in [GitHub's documentation](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions)

Use commit hashes for action references

---

.github/workflows/label-sync.yml

GitHub recently introduced a breaking change that causes workflows referencing Actions by tag SHA to fail. This pull request resolves this issue by changing all Action references to commit SHAs.

Use commit SHA for workflows

---

Makefile
deploy/ccm-linode-template.yaml
main.go

Resolves #91
This change hardcodes some flags. Setting `--authentication-skip-lookup=true` short circuits configmap lookup for authentication (no longer needed), allowing for more fine-grained permissions. Also hardcodes --cloud-provider to "linode".
The manifest template has also been updated to use a restricted clusterrolebinding.

Hardcode --authentication-skip-lookup=true to short-circuit ConfigMap auth

---

go.mod
go.sum

Bumps linodego from `v0.21.1` to `v0.32.2`. [Lots of changes](https://github.com/linode/linodego/compare/v0.21.1...v0.32.2) -- e2e tests are passing.

bump linodego to v0.32.2

---

README.md

Removes references to `dep` and provides link to Go Modules documentation.
Fixes typo in Build Binary section.
Closes #104

update development steps in README.md

---

cloud/linode/fake_linode_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Filter NodeBalancers when we know their ipv4

---

cloud/linode/fake_linode_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

If a service is not annotated, the two calls to new/old NBs will inevitably return the very same NB, so not NBs will get deleted in that method. We can thus short circuit this and not proceed to the API calls unless we have an annotation present within the service.
1. [ ] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pul …

Short circuit LB cleanup if no annotations present

---

cloud/linode/common.go
cloud/linode/instances.go
cloud/linode/instances_test.go

Since we call the individual "get instance" API call very frequently, we could instead call a single "list instances" once and reuse that for all the Linode lookups. This is essentially a client-side cache.
We won't reduce traffic between us and the Linode API (we'll probably increase it a bit), but we'll cut down the number of calls quite dramatically.
1. [x] Have you …

Cache node listings instead of random lookups

---

README.md
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml

Adding the ability to set the Hostname Only Ingress vian ENVVARS because Gateway API does not yet support annotations.
See the conversation over at cilium: https://github.com/cilium/cilium/issues/25357

Adding an environment vairiable to change default hostname only ingress abilities.

---

.github/workflows/test.yml
Makefile
deploy/chart/templates/ccm-linode.yaml
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml

Adding support for passing the LinodeAPIToken and region via secret references instead of raw helm values. This prevents the disclosure of the token in values files when using gitops practices.

Allow passing linodeApitoken and region as secretRef

---

README.md
cloud/linode/fake_linode_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Support adding tags to a nodebalancer - supply a comma-separated string in an annotation to a service of type `LoadBalancer` to automatically add tags to the created node-balancer resource. Fixes #137 

Support adding tags to nodebalancers

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Should our list of `nodes` be empty, we shouldn't reconfigure our NBs, because we can't call the Linode endpoint with an empty list of nodes.

Do not ensure/update LBs if nodes are empty

---

README.md
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Fixes #111
Kubernetes node internal IP addresses are not necessarily Linode Private IPs, which must be used for NodeBalancers to communicate with a node. This allows specifying the IP with an annotation in such cases.
Manually set the annotation to on …

Allow specifying Private IP by annotation for VLAN / VPC support

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Nodebalancer backends can have a max label length of 32 chars.
If a k8s node's name is longer than 32 chars, creating a nodebalancer fails.
Example error:
```console
E0307 22:31:47.275176       1 controller.go:307] error processing service traefik/traefik (will retry):
failed to ensure load balancer: [400] [configs[0].nodes[0].label] Length must be 3-32 characters;
[configs[0].nodes[1].label] Length must be 3-32 characters;
[configs[0].nodes[2].label] Length must be 3-32 characters;
```
1. [X] Have you saved your large formatting changes for …

feat: truncate long labels in nodebalancers

---

Makefile
cloud/linode/cloud.go
cloud/linode/loadbalancers.go

* set unused func params to _
* rewrite ok logic to remove superfluous else

upgrading golangci-lint to v1.55.2

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

automatically add the cluster name as a tag to the created/updated nodebalancers
fixes #150

add cluster name as a tag to nodebalancers

---

e2e/test/ccm_e2e_test.go

These Gomega patterns are hard to debug, remove these in favour of `Equal` calls.

Remove BeTrue patterns from e2e tests

---

.golangci.yml
Makefile
cloud/linode/common_test.go
cloud/linode/fake_linode_test.go
cloud/linode/instances_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
e2e/test/ccm_e2e_test.go
e2e/test/ccm_suite_test.go
e2e/test/framework/service.go
e2e/test/framework/util.go

There are three issues with linting atm:
- we have a set of pretty lax rules
- some of the linters used are deprecated
- we do not lint e2e tests
I am to fix all these issues in this PR. Note that I had to disable the ginkgo linter, because it flagged issues that we're working on in #158.

Stricter linting

---

Makefile
cloud/linode/annotations.go
cloud/linode/client.go
cloud/linode/cloud.go
cloud/linode/instances.go
cloud/linode/loadbalancers.go
cloud/linode/node_controller.go

---
A host UUID was added to the Linode Instance in a client change: https://github.com/linode/linodego/pull/284
Apply this UUID from the CCM to expose the underlying host uniqueness, can improve scheduling and placement decisions for resources …

feat: add linode UUID as a metadata to each node

---

cloud/linode/instances.go
cloud/linode/node_controller.go

**BUGFIX:** This code change involves modifying the logic for handling metadata updates for Linode instances in a Kubernetes cluster. Previous behaviour spammed, did redundant work on Create and Update, and every time it was triggered, it pulled the …

fix: metadata TTL

---

cloud/linode/common.go
cloud/linode/instances.go
cloud/linode/instances_test.go

Fixes a bug where the host-uuid was not set correctly for non-LKE clusters. 

fix: set host-uuid correctly on non LKE clusters

---

cloud/linode/loadbalancers.go

Remove a helper method and replace it with native kube functions. 

Replace helper

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
e2e/test/ccm_e2e_test.go
e2e/test/framework/service.go

Found an edge case where I had deleted a nodebalancer but it was set on a service and wouldn't clear the finalizer and never saw the short-circuit log from here: https://github.com/linode/linode-cloud-controller-manager/blob/main/cloud/linode/loadbalancers.go#L413
the lbnotfound type check was rewriting to a new error and never returning so moving the onus on checking lbnotfound to the create path so a second load balancer is not created and the skip now works.

always return lbnotfound from getNodeBalancerForService

---

cloud/linode/loadbalancers.go

Addresses an issue where a long k8s service name will create firewall rules labels that are too long (Linode API accepts max 32 chars). This strips the name when too long, leaves it untouched otherwise
fixes #172 

fix firewall label length being too long with large svc names

---

.github/workflows/helm.yml
README.md
deploy/chart/Chart.yaml
deploy/chart/values.yaml

This PR adds a workflow for us to test and release our helm chart to a GH page in this repo using [this action](https://github.com/helm/chart-releaser-action)

add helm test and publish workflow

---

cloud/linode/node_controller.go

We sometimes see issues where there is a resource version conflict in the logs so this would fix such issues. 

Wrap node update in retry

---

deploy/ccm-linode-template.yaml
deploy/chart/values.yaml

The selector for the CCM should be updated to account for the [deprecation and removal](https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-master-taint) of the `master` node-role. Currently, this doesn't work out-of-the-box on k8s 1.29 which uses only `node-role.kubernetes.io/control-plane` for control plane nodes.

update default CCM node selector and tolerations from master to control-plane

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go

Adds support for firewall ACL with >255IPs, building intelligence into the ccm to break it up into chunks of ips.
Implemented an ip-split mechanism. will be adding a e2e test for the firewall feature as a whole shortly.

Support for acls with >255 IPs

---

README.md
cloud/linode/client/client.go
cloud/linode/client/mock_client_test.go
cloud/linode/cloud.go
cloud/linode/instances.go
cloud/linode/instances_test.go
cloud/linode/mock_client_test.go
cloud/linode/route_controller.go
cloud/linode/vpc.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
main.go

**What type of PR is this?**
/kind feature
**What this PR does / why we need it:**
Cloud-controller-manager provides [interfaces](https://github.com/kubernetes/cloud-provider/blob/v0.23.17/cloud.go#L230-L240) to implement functionality of managing routes in cluster. For k8s clusters provisioned within VPC, we need to automatically add/remove podCIDRs allocated to nodes to the linode's interface configs so that the traffic can be routed within the VPC. This PR implements the Routes interfaces.
This PR also makes sure that if a node is a part of VPC, then VPC ip is shown as the node internal ip.
```
root@rah6-control-plane-bjwwd:~# k get nodes -o wide
NAME                       STATUS   ROLES           AGE    VERSION   INTERNAL-IP   EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION …
```

feat: add route-controller to linode ccm

---

cloud/linode/route_controller.go

We added route_controller to linode ccm. It is disabled by default and enabled when specific flags are specified. We ended up introducing a bug where if its disabled by default, it keeps crashing as it tries to check for VPC info which it shouldn't care if route_controller is disabled. This PR fixes it.
1. [ ] Have you linked your PR to an [open …

don't error out with empty vpc name if routecontroller is disabled

---

cloud/linode/instances.go
cloud/linode/instances_test.go
cloud/linode/node_controller.go

This change adds a `lookupByIP` function if a linode cannot be found by label or ID. This means rather that as long as the node and linode share an IP address it will be able to lookup the linode. additionally, we now set the ProviderID based on this lookup if it is not already set so future lookups only need to be made against the ID.
1. [ ] Have you linked your PR to …

Lookup linode by IP instead if label or providerID do not match

---

deploy/chart/templates/daemonset.yaml

…ound for issue #200 which some users are experiencing

Adding --webhook-secure-port=0 to helmchart since it is needed workaround for issue #200

---

e2e/go.mod
go.mod

My go can't download toolchain:
```bash
go env
go: downloading go1.22 (linux/amd64)
go: download go1.22 for linux/amd64: toolchain not available
```
Here is the answer why: https://github.com/golang/go/issues/62278#issuecomment-1693538776
Fixes: https://github.com/linode/linode-cloud-controller-manager/issues/202
1. [X] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [X] Have you explained your rationale for why this feature is needed? 
1. [X] Have you linked your PR to an [open …

Set toolchain go1.22.2 go.mod

---

cloud/linode/client/client.go

Currently the regex for parsing the `LINODE_URL` env var does not work for the v4beta version of the Linode API. This makes it so v4beta can be used if needed (see https://github.com/linode/linodego/blob/main/client.go#L149).

update client to work for v4beta API

---

cloud/linode/service_controller.go

There's currently a bug that leaves an orphaned NodeBalancer if a Service's type changes to no longer be `LoadBalancer`. If the type is changed back, a new NodeBalancer is created. 
This PR detects a change in Service type and deletes the NodeBalancer if necessary.
e.g. when doing a `kubectl edit` on a Service to instead be a NodePort type:
```
I0521 14:43:02.423709       1 service_controller.go:61] ServiceController will handle service (test-ns2/test-svc) LoadBalancer deletion
I0521 14:43:02.423736       1 service_controller.go:111] ServiceController handling service (test-ns2/test-svc) deletion
I0521 14:43:02.424889       1 controller.go:969] Removing finalizer from service test-ns2/test-svc
I0521 14:43:02.425893       1 event.go:376] "Event occurred" object="test-ns2/test-svc" …
```

[bugfix] - handle LoadBalancer deletion if service type changes to no longer be a LoadBalancer

---

cloud/linode/firewall/firewalls.go
cloud/linode/loadbalancers_test.go

Currently when you remove a `service.beta.kubernetes.io/linode-loadbalancer-firewall-acl` annotation from a service, the ccm attempts to use the NodeBalancerID when attempting to delete the device which results in a 404 from the Linode API which …

fix: remove firewall device by device ID not entity ID

---

cloud/linode/cilium_loadbalancers.go
cloud/linode/cilium_loadbalancers_test.go

This handles the edge case of shared IPs no longer being held by the ip-holder nanode due to someone manually deleting the IP outside of the CCM logic. Thanks @rahulait for finding this!

[fix] don't try to share IPs that may have been removed on the ip-holder outside of the CCM logic

---

.github/workflows/helm.yml

https://github.com/linode/linode-cloud-controller-manager/pull/179 should have restricted helm-releases to be kicked off via the release workflow, but when the happens github.ref gets set to the git ref of the newly created tag and is no longer main. …

fix: use tag ref for helm-release so the release workflow can start it

---

cloud/linode/instances.go
cloud/linode/instances_test.go

This updates Nodes to also have their ipv6 address set for their external IPs to support dual-stack / ipv6-enabled clusters.

include ipv6 address for node external IPs

---

README.md
cloud/linode/client/client.go
cloud/linode/cloud.go

We see cloud-controller-manager stuck for 10-15 mins when doing vpcless installs with firewalling enabled using cluster-api-provider-linode. Upon further troubleshooting, we see some calls getting stuck for more than 10 mins:
```
2024/06/17 13:23:11.262239 DEBUG RESTY
==============================================================================
~~~ REQUEST ~~~
GET  /v4/linode/instances  HTTP/1.1
HOST   : api.linode.com
HEADERS:
Accept: application/json
Authorization: Bearer XXXX
Content-Type: application/json
User-Agent: linode-cloud-controller-manager linodego/v1.33.0 https://github.com/linode/linodego
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
PROTO        : HTTP/1.1
RECEIVED AT …
```

add timeout for linodego http client

---

cloud/linode/cilium_loadbalancers.go
cloud/linode/cilium_loadbalancers_test.go

This change enables shared IP loadbalancing across all nodes whenever no `bgpNodeSelector` is specified; i.e. by default.

feat: Support high performance ingress with no label selector

---

cloud/linode/node_controller.go

Sometimes the metadata might become stale when the node itself is not removed/added or even updated. We need to trigger the update to prevent stale metadata on the nodes.

fix: refresh node metadata on stale nodes

---

cloud/linode/client/client.go

We're hitting the same issue as here: https://github.com/linode/cluster-api-provider-linode/pull/436
When we use a custom CA, it doesn't get used.
Given that we construct an http.Transport that is of a different concrete type than http.Transport (it just needs to be a RoundTripper), resty fails and defaults to an empty client, discarding our CA.
1. [x] Have you linked …

Do not use a custom http.Transport due to Resty incompatibility

---

cloud/linode/cilium_loadbalancers.go

Addresses edge cases where the ip-holder does not immediately reflect the new IP address that was added to perform IP sharing

[fix] don't assume the IP holder immediately reflects the new IP to share for a cilium-bgp-lb Service

---

README.md
cloud/linode/cloud.go
cloud/linode/common.go
cloud/linode/instances.go
cloud/linode/instances_test.go
cloud/linode/node_controller.go
main.go

With new enviroment variable `LINODE_EXTERNAL_SUBNET` is possible to set internal network subnet to be used as external network.
Useful for running on testing Linode cloud instances which are providing external IP addresses in internal network.

Allow to mark internal network as external

---

cloud/linode/cilium_loadbalancers.go
cloud/linode/cilium_loadbalancers_test.go

1. [X] Have you added tests? 
1. [X] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [X] Have you explained your rationale for why this feature is needed? 
1. [X] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)
Calls to `getExistingSharedIPs` should return Public IPs instead of Shared IPs, because the IPs on the holder nanode are not returned under the Shared IP's section of the API response.
fixes #231

[fix] getExistingSharedIPs should get Public IPs from the holder

---

cloud/linode/instances.go
cloud/linode/instances_test.go

Related to #111 
In the case that a Node's internal IP is already set (e.g. to a VLAN IP), the CCM will fail to set the external IP for the Node:
```
E1001 18:20:24.780329       1 node_controller.go:240] error syncing 'foo-control-plane-kxlgm': failed …
```

[fix] handle cases where the internal-ip is already set (e.g. kubelet)

---

.golangci.yml
cloud/linode/fake_linode_test.go

This removes types that have been deprecated in more recent versions of linodego for PagedResponses. (see https://github.com/linode/linodego/blob/v1.41.0/request_helpers.go#L13-L18)

[cleanup] remove deprecated PagedResponse types from fake_linode_test

---

deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml

make volume and volume mounts configurable through helm

---

.gitignore
Makefile
devbox.json
devbox.lock

[feat] add support for devbox

---

README.md
cloud/linode/cloud.go
cloud/linode/instances.go
cloud/linode/route_controller.go
cloud/linode/route_controller_test.go
cloud/linode/vpc.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
main.go

This PR enables route-controller to manage instances running in multiple vpcs. All these instances should still be part of a single k8s cluster where the CCM is running.
This change introduces a new flag `vpc-names` which is a comma separated list of vpc names which will be managed by the CCM's route-controller. Old flag `vpc-name` is now deprecated and will be removed in future releases.
Changes in this branch are present in helm chart here: https://github.com/rahulait/linode-cloud-controller-manager/releases/tag/helm-v0.4.16
If one wants to test these changes, simply use helm repo https://rahulait.github.io/linode-cloud-controller-manager/ with version v0.4.16 to test the changes before we merge this branch to main.
1. [ ] Have you added tests? …

manage routes for instances in multiple vpcs in a single region

---

cloud/linode/cilium_loadbalancers.go

Update Cillium LoadBalancer regionIDMap to be up-to-date with available docs [1].
[1] https://techdocs.akamai.com/cloud-computing/docs/configure-failover-on-a-compute-instance#ip-sharing-availability

Update Cillium LoadBalancer regionIDMap

---

cloud/linode/instances.go
cloud/linode/instances_test.go

Node's internal ip is set based on whatever ip is returned as first internal ip. In case of VPC, we always want that ip to be node's internal ip. We do that ordering when returning node's ip-addresses. However, we were storing things in map and re-generating which was changing the order. Instead, we can just rely on map to tell if its unique or not and then append to the slice. This PR fixes that by making sure node's actual ip's are listed first and then the ones set by kubelet.
1. [x] Have you saved your large formatting changes for a …

[fix] : fix internal ip ordering

---

.github/filters.yml
.github/workflows/ci.yml
Makefile
cloud/linode/cloud.go
devbox.json
e2e/setup/ctlptl-config.yaml
main.go

Fixes https://github.com/linode/linode-cloud-controller-manager/issues/145
This PR enables running ccm e2e tests against a CAPL deployed cluster.

[repo-ci-improvement] : update GHA to run e2e tests

---

deploy/ccm-linode-template.yaml
deploy/generate-manifest.sh

Fixes https://github.com/linode/linode-cloud-controller-manager/issues/249 and https://github.com/linode/linode-cloud-controller-manager/issues/250
This PR updates the template which is used by script to generate manifests for linode-ccm.

[fix] : fix template for linode ccm

---

.github/PULL_REQUEST_TEMPLATE.md
.github/labels.yml
.github/release-drafter.yml
.github/workflows/pr-labeler.yml
.github/workflows/release-drafter.yml

Adding release-drafter to CCM repo

[repo-ci-improvement] : add release-drafter to ccm

---

e2e/test/route-controller-test/chainsaw-test.yaml

[testing] E2E test case for VPC route controller 

---

.github/workflows/ci.yml
cloud/linode/vpc_test.go

[test] : add unittests for vpc.go file

---

cloud/linode/service_controller_test.go

[test] : add unittest for service controller

---

cloud/linode/node_controller_test.go
cloud/linode/service_controller.go

This PR adds unittests for node_controller.go file

[test] : add unittests for node_controller

---

e2e/test/fw-use-specified-nb/chainsaw-test.yaml
e2e/test/lb-http-body-health-check/chainsaw-test.yaml
e2e/test/lb-http-status-health-check/chainsaw-test.yaml
e2e/test/lb-passive-health-check/chainsaw-test.yaml
e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
e2e/test/lb-with-http-to-https/chainsaw-test.yaml
e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
e2e/test/lb-with-node-addition/chainsaw-test.yaml

Sometimes, e2e test would fail even if its within a forloop block to retry few times. If curl command returned non-zero code, it would result in script to fail. With these fixes, we are now letting code to retry few times based on the for loop.

[test] : fix random failures in e2e tests due to curl error

---

README.md
cloud/linode/cilium_loadbalancers.go
cloud/linode/cilium_loadbalancers_test.go

This PR adds support for two new environment variables in the following formats `BGPPeerPrefix="2600:3c0f"` and `BGPCustomIDMap='{"nl-ams": 22, "us-southeast": 4}'` which combined allows for custom BGP environments.

[feat] add support for custom BGP environment overrides via environment variables

---

cloud/linode/cilium_loadbalancers.go

Use default values if env var is set but is empty.

[fix] : ignore if env vars are empty

---

Makefile
sentry/sentry_test.go

[test] Add unit test cases for Sentry

---

cloud/linode/firewall/firewalls.go
cloud/linode/loadbalancers_test.go
e2e/test/lb-fw-update-acl/chainsaw-test.yaml
e2e/test/lb-fw-update-acl/create-pods-services.yaml
e2e/test/lb-fw-update-acl/update-service.yaml

If a firewall is created by CCM, it failed to get updated if ip's were removed from its ACL. For example:
```
kind: Service
apiVersion: v1
metadata:
name: https-lb
annotations:
service.beta.kubernetes.io/linode-loadbalancer-firewall-acl: |
{
"denyList": {
"ipv4": ["8.8.8.8/32",
"9.9.9.9/32",
"7.7.7.7/32"]
}
}
spec:
type: LoadBalancer
selector:
app: apache
ports:
- name: http
protocol: TCP
port: 80
targetPort: 80
- name: https
protocol: TCP
port: 443
targetPort: 443
```
The above example would create a service of type loadbalancer and have the nodebalancer port secured using a firewall with denylist as listed in the example. However, when ip's were removed from this denylist and re-applied, it was not updating the firewall on linode API. CCM was failing to identify that ip has been removed …

[fix] : fix ACL update bug

---

cloud/linode/client/client.go
cloud/linode/client/mocks/mock_client.go
cloud/linode/cloud.go
cloud/linode/health_check.go
cloud/linode/health_check_test.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
main.go

Sometimes it happens that the LINODE API TOKEN used by ccm expires or is revoked. This can go unnoticed for long periods since the only mechanism in place is logging it when actual call to Linode API fails. This PR implements health checker component that periodically makes calls to authenticated linode api endpoint (/v4/profile) to determine validity of token being used. Upon detection of invalid token health checker sends a signal to shut down controllers. This results in ccm Pod CrashLoopBackOffing which is greatly visible and can be acted upon. Health checker is only started when the controller is elected the leader. This reduces number of calls done to Linode API if there are multiple replicas of ccm. Whole health checker functionality is behind `--enable-token-health-checker` flag …

[feat] add linode token health check

---

.github/workflows/ci.yml
e2e/test/lb-fw-delete-acl/chainsaw-test.yaml

We now have two environments (prod and prod-external). We should use prod-external for any PR coming from a forked repo and trying to access secrets as we have protection rules requiring manual approval before a GHA can run and access secrets for this environment.
1. [ ] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pull …

add environment for e2e tests

---

deploy/ccm-linode-template.yaml
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml

This PR adds compatibility for clusters running RKE2 on top of Linode infrastructure without needing to modify the manifests or helm chart values. Security contexts are set for the case of running with CIS hardening on RKE2 clusters.

[improvement] set securityContext and use affinity instead of nodeSelector

---

.github/workflows/ci.yml

Currently, since it uses main branch because of `pull_request_target`, all PRs are building image with `latest` tag and are also affecting concurrent runs as the group is turning out to be same for all. This PR addresses those issues.

[CI] : fix image used by ci and concurrency of gha runs

---

deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
docs/getting-started/helm-installation.md

This PR allows Helm chart consumers to set `vpcName(s)` without enabling the route controller. The chart will still error if `routeController` is set to true but no VPC is specified. This change allows the node controller to only cache nodes that …

[improvement] Allow setting vpcName(s) without enabling route controller

---

deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml

Allow setting container resource requests and limits

Add resources to container

---

Makefile
cloud/annotations/annotations.go
cloud/linode/fake_linode_test.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
docs/configuration/annotations.md
docs/configuration/loadbalancer.md
e2e/test/lb-with-vpc-backends/chainsaw-test.yaml
e2e/test/lb-with-vpc-backends/create-pods-services.yaml
go.mod
go.sum
main.go

This PR allows nodebalancer backends to be configured directly with VPC if specific annotations are added to the service.

[feat] : add support for configuring nodebalancers with VPC

---

cloud/annotations/annotations.go
cloud/linode/cloud.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
docs/configuration/README.md
docs/configuration/annotations.md
docs/configuration/environment.md
docs/configuration/loadbalancer.md
main.go

Implement a new flag `--enable-ipv6-for-loadbalancers` to allow adding IPv6 addresses for LoadBalancer services. Also, added support to enable it per service using an annotation (`service.beta.kubernetes.io/linode-loadbalancer-enable-ipv6-ingress`). This feature provides flexibility for users who prefer IPv6 networking, with the following changes:
- Add `UseIPv6ForLoadBalancers` option to Linode cloud provider options
- Modify `makeLoadBalancerStatus` to add IPv6 address when the flag is set
- Add a new test case to verify IPv6 address selection
- Update documentation to explain the new IPv6 configuration option
1. [x] Are your commits atomic, addressing one change …

[feat] Add IPv6 ingress address support for NodeBalancer services

---

cloud/linode/cloud.go
cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
docs/configuration/environment.md
docs/configuration/loadbalancer.md
main.go

If CCM is started with `--nodebalancer-backend-ipv4-subnet` flag, then it will not allow provisioning of nodebalancer unless subnet specified in service annotation lie within the subnet specified using the flag. This is to prevent accidental overlap between nodebalancer backend ips and pod CIDRs.
1. [ ] Have you linked your PR to an [open …

[improvement] : add flag to set nodebalancer subnet

---

.golangci.yml
cloud/linode/cilium_loadbalancers.go
cloud/linode/cilium_loadbalancers_test.go
cloud/linode/client/client.go
cloud/linode/cloud.go
cloud/linode/cloud_test.go
cloud/linode/fake_linode_test.go
cloud/linode/firewall/firewalls.go
cloud/linode/health_check.go
cloud/linode/health_check_test.go
cloud/linode/instances.go
cloud/linode/instances_test.go
cloud/linode/loadbalancers.go
cloud/linode/metrics.go
cloud/linode/node_controller_test.go
cloud/linode/service_controller.go
cloud/linode/service_controller_test.go
cloud/linode/vpc.go
cloud/linode/vpc_test.go
main.go

This is the first part of updating this repository's golangci-lint configuration. This PR adds multiple new linters and configures others. Some linters are temporarily disabled so that CI continues to pass without overhauling the repository in a massive PR.
This PR also addresses the linting errors that can be fixed by running golangci-lint with the `--fix` flag, as well as errors from the following linters:
- nolintlint
- goconst (WIP)
[ ] Does your submission pass tests?
[X] Are you addressing a single feature in this PR? 
[ ] Are your commits atomic, addressing one change per commit?
[X] Are you following the conventions of the language?

[CI] Golangci-lint update part 1 

---

cloud/linode/instances_test.go
cloud/linode/node_controller.go
cloud/linode/node_controller_test.go

This PR now makes sure most recent node request is processed. Currently, in case of 429 or 5XX errors, we are re-queueing the request after a minute to retry again. If linodeAPI is down for some reason or we are getting rate limited, those requests will get re-queued. We also get node update requests every 5 mins and if they also fail, they also end up getting queued. We saw that we were making multiple requests again and again which kept on increasing over time when we encountered 429 or 5XX API errors. This PR addresses that and keeps track of time when the most recent node update request was made for a node. All prior requests which are in queue or are waiting to be queued due to AddAfter() will get ignored once it tries to process them and will always process the most recent request. …

[fix] : use latest node object when processing node update request

---

cloud/linode/node_controller.go
cloud/linode/node_controller_test.go
cloud/linode/route_controller.go
cloud/linode/route_controller_test.go
docs/configuration/environment.md
e2e/test/route-controller-test/chainsaw-test.yaml

This PR makes sure we don't delete routes from ip_ranges if someone accidentally changes linode label. This PR introduces k8s cache which stores node objects and their linode specific providerIDs and uses them when building list of routes or creating routes.
1. [ ] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pull-reque …

[fix] : add k8s node cache and prefer providerID for node search

---

cloud/linode/node_controller.go

This fix adds a timeout for listNodes k8s call so that if apiserver is not responding, the call should timeout after some time and not hang indefinitely somehow.

[fix] : add context timeout to prevent node_controller for hanging

---

.github/workflows/nightly-merge.yml

This PR adds the nightly merge workflow to the CI pipeline to automatically merge changes to main into the gh-pages branch. This is to prevent documentation from becoming out of date and to avoid needing to manually merge changes.
1. [X] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [X] Have you explained your rationale for why this feature is needed?

[CI] Add nightly merge workflow for gh-pages

---

cloud/linode/route_controller.go
cloud/linode/route_controller_test.go

Currently, route_controller will attempt to create routes for IPv6 pod CIDRs and will fail, which means it will retry indefinitely (see logs below). IPv6 routes don't need to be configured because of the huge address space available, so this PR updates CCM route_controller to effectively ignore IPv6 CIDRs. This is done by adding the route to a local cache of "configured" routes, then appending those routes to the list of configured routes returned by ListRoutes. This tells route_controller that the route has been configured, but no configuration has actually been made.
```
I0402 16:24:49.847301       1 route_controller.go:214] action for Node "ccm-717a8f3-md-0-qzzm2-nx6vj" with CIDR "10.192.2.0/24": "keep"
I0402 16:24:49.847305       1 route_controller.go:214] action for Node …
```

[fix] Ignore ipv6 routes

---

e2e/test/lb-http-body-health-check/chainsaw-test.yaml
e2e/test/lb-http-status-health-check/chainsaw-test.yaml
e2e/test/lb-passive-health-check/chainsaw-test.yaml
e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml
e2e/test/lb-with-http-to-https/chainsaw-test.yaml
e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
e2e/test/lb-with-node-addition/chainsaw-test.yaml

We have seen some e2e tests fail randomly. This PR adds more logs and also lets those tests to run a bit longer to see if that helps.

[CI] : add logs for e2e tests for easier debugging

---

cloud/linode/loadbalancers.go
cloud/linode/node_controller.go
cloud/linode/service_controller.go

As mentioned in [PR 349](https://github.com/linode/linode-cloud-controller-manager/pull/349), several errorlint errors were ignored because attempting to fix them resulted in two chainsaw tests breaking. This PR resolves the errorlint errors so we avoid issues with wrapped errors.
1. [X] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [X] Have you explained your rationale for why this feature is needed?

[improvement] Refactor code blocks ignored by errorlint

---

cloud/linode/firewall/firewalls.go
cloud/linode/firewall/firewalls_test.go
e2e/test/lb-update-port/chainsaw-test.yaml
e2e/test/lb-update-port/create-pods-services.yaml
e2e/test/lb-update-port/update-port-service.yaml

Previously, updateNodeBalancerFirewallWithACL only considered ACL IP annotation changes and never updated firewall rules when Service ports were added or removed—leading to stale or unintended open ports.
This commit:
- Rebuilds the complete desired rule set (Service.Spec.Ports + ACL)
- Compares existing inbound rules vs. desired
- Extends ruleChanged to detect both IP and port modifications
- Adds unit tests
1. [x] Have you explained your …

[fix] reconcile NodeBalancer firewall rules on port changes

---

deploy/chart/templates/daemonset.yaml

This PR adds quotes around the port since that is usually a number and env values can not be numbers. 

Bug: add quote to k8s-service-port

---

cloud/linode/loadbalancers.go
cloud/linode/loadbalancers_test.go
e2e/test/lb-with-node-addition/chainsaw-test.yaml

Upstream controller keeps a [serviceCache](https://github.com/kubernetes/cloud-provider/blob/v0.33.2/controllers/service/controller.go#L83) which never gets updated when the service is updated.
When a service is created for the first time, it doesn't have any status field set. It gets stored in the serviceCache of upstream controller. Upon any update to service, this service object gets passed to functions implemented by individual cloud providers (CCM in our case). If there is any error during update, it returns an error and then calls [GetLoadBalancer](https://github.com/kubernetes/cloud-provider/blob/v0.33.2/controllers/service/controller.go#L851) and passes service object to it. In our implementation of [GetLoadBalancer](https://github.com/linode/linode-cloud-controller-manager/blob/v0 …

[fix] : use updated service status as upstream controller can pass wrong info

---

cloud/linode/cloud.go
cloud/linode/cloud_test.go
cloud/linode/loadbalancers.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
docs/configuration/environment.md
main.go

This PR introduces a flag that allows you to replace the "ccm-" prefix with any string of up to 20 characters.
This change allows you to set a cluster name as a prefix and trace Node Balancers more easily.
General:
1. [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
1. [x] Have you checked to ensure there aren't other open or closed [Pull Requests](https://github.com/linode/pulls) for the same bug/feature/question?
1. [x] Have you saved your large formatting changes for a different PR, so …

[feat]: Add custom prefix for load balancer

---

cloud/linode/cloud.go
cloud/linode/cloud_test.go
deploy/chart/templates/daemonset.yaml
deploy/chart/values.yaml
main.go

Its been more than 8+ months since we deprecated vpcname flag. This PR removes the deprecated flag.

[improvement] : remove deprecated vpcname flag

---

cloud/linode/client/client.go
cloud/linode/client/client_with_metrics.go
cloud/linode/client/mocks/mock_client.go
cloud/linode/route_controller.go
cloud/linode/route_controller_test.go
cloud/nodeipam/ipam/cloud_allocator.go
cloud/nodeipam/ipam/cloud_allocator_test.go

[Linode Interfaces is in beta](https://techdocs.akamai.com/linode-api/reference/post-linode-interface). This adds support so the CCM can work on Linodes using the new linode interfaces.
**NOTE**: If you want to test this locally you need to opt in to the Linode Interfaces beta AND the ability to use VPC-only backends (see https://github.com/linode/cluster-api-provider-linode/pull/803).
1. Make a CAPL cluster that uses the new network interfaces (follow the Testing section in https://github.com/linode/cluster-api-provider-linode/pull/821) but update the test-cluster.yaml BEFORE APPLYING IT to have the following:
- `adumaine/linode-cloud-controller-manager:linode-interfaces` for the CCM repo and version, e.g.:
```
<snip>
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy …
```

[feat] add support for using linode interfaces (beta-only)

---

cloud/nodeipam/ipam/cloud_allocator.go
cloud/nodeipam/ipam/cloud_allocator_test.go
docs/configuration/nodeipam.md

- Add computeStableIPv6PodCIDR() to derive a stable /112 from a node’s /64 using mnemonic subprefix :0:c::/112.
- allocateIPv6CIDR(): prefer stable subprefix when mask=112 and base is /64; otherwise fall back to start-of-range masking.
- Update tests in cloud/nodeipam/ipam/cloud_allocator_test.go to expect 2300:5800:2:1:0:c::/112.
- Document behavior and correct example flag to --node-cidr-mask-size-ipv6=112 in docs/configuration/nodeipam.md.
- Add/adjust debug logs for clarity; no change to IPv4 behavior.
1. [x] Have you saved your large …

[improvement][feat] Deterministic IPv6 /112 PodCIDR via :0:c::/112; update tests/docs
